### ISSUE TITLE
got unknown error while etting the reminder

### ISSUE THREAD

**Issue by khegde22** [ssheftel/skill-demo-remindify#1]
I used same code provided in this repository. I am getting below error while setting reminder.
please assist.
(Note : I have successfully achieved the 'permission' part for reminder)

Response:
{
  "version": "1.0",
  "sessionAttributes": {},
  "userAgent": "ask-python/1.13.0 Python/3.6.10",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak>Sorry, there was some problem. Please try again!!</speak>"
    },
    "reprompt": {
      "outputSpeech": {
        "type": "SSML",
        "ssml": "<speak>Sorry, there was some problem. Please try again!!</speak>"
      }
    },
    "shouldEndSession": false
  }
}

Request ID:
"7b30aa9a-3e20-4834-a427-7f2b7ec5f2e6"

Function Logs:
START RequestId: 7b30aa9a-3e20-4834-a427-7f2b7ec5f2e6 Version: $LATEST
[ERROR]	2020-02-13T05:24:27.623Z	7b30aa9a-3e20-4834-a427-7f2b7ec5f2e6	Unknown error
[ERROR]	2020-02-13T05:24:27.640Z	7b30aa9a-3e20-4834-a427-7f2b7ec5f2e6	Unknown error
Traceback (most recent call last):
  File "/opt/python/ask_sdk_runtime/dispatch.py", line 118, in dispatch
    output = self.__dispatch_request(handler_input)  # type: Union[Output, None]
  File "/opt/python/ask_sdk_runtime/dispatch.py", line 183, in __dispatch_request
    handler_input=handler_input, handler=request_handler)  # type: Union[Output, None]
  File "/opt/python/ask_sdk_runtime/dispatch_components/request_components.py", line 437, in execute
    return handler.handle(handler_input)
  File "/opt/python/ask_sdk_runtime/skill_builder.py", line 156, in <lambda>
    handler_input)
  File "/var/task/test.py", line 69, in notify_me_intent_handler
    raise e
  File "/var/task/test.py", line 65, in notify_me_intent_handler
    reminder_responce = reminder_service.create_reminder(reminder_request)
  File "/opt/python/ask_sdk_model/services/reminder_management/reminder_management_service_client.py", line 382, in create_reminder
    response_type="ask_sdk_model.services.reminder_management.reminder_response.ReminderResponse")
  File "/opt/python/ask_sdk_model/services/base_service_client.py", line 158, in invoke
    headers=response.headers, body=response.body)
ask_sdk_model.services.service_exception.ServiceException: Unknown errorEND RequestId: 7b30aa9a-3e20-4834-a427-7f2b7ec5f2e6

**Comment by khegde22** [comment]
Reminder has not enabled in the device, once it enabled issue resolved.
